version: '2.1'

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.02.1
    # resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: show cwd
          command: ls
      - run:
          name: Using Buildx for docker
          command: |
            docker buildx create --use
      - run:
          name: Login to cloud.canister
          command: |
            docker login --username $DOCKER_LOGIN --password $DOCKER_PWD cloud.canister.io:5000
      - run:
          name: Build Docker image
          command: |
            docker buildx build --platform=linux/amd64,linux/arm64 -t "${CLOUD_CANISTER_URL}:latest" --push .
      # - run:
      #     name: Push Docker image to cloud.canister
      #     command: |
      #       docker push "${CLOUD_CANISTER_URL}:latest"
  
  deploy:
    machine:
        enabled: true
    steps:
      - run:
          name: get new docker image
          command: |
            ssh $SSH_USER@$SSH_HOST "sudo docker pull ${CLOUD_CANISTER_URL}:latest"
      - run:
          name: remove old docker image
          command: |
            ssh $SSH_USER@$SSH_HOST "sudo docker container stop ${CONTAINER_NAME} || true"
            ssh $SSH_USER@$SSH_HOST "sudo docker container rm ${CONTAINER_NAME} || true"
      - run:
          name: deploy docker image
          command: |
            ssh $SSH_USER@$SSH_HOST "sudo docker run -d --name ${CONTAINER_NAME} -e mongodb_url=${mongodb_url} -p ${deployment_port} --restart unless-stopped ${CLOUD_CANISTER_URL}:latest"
      - run:
          name: prune unused docker images
          command: |
            ssh $SSH_USER@$SSH_HOST "sudo yes Y | sudo docker image prune -a"


workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - build:
         filters:
           branches:
             only:
               - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
        

#  